# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random
import sys

from PyQt5 import uic
from PyQt5.QtGui import QPainter, QPen, QColor, QBrush
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.qwer = QtWidgets.QPushButton(self.centralwidget)
        self.qwer.setGeometry(QtCore.QRect(310, 360, 151, 41))
        self.qwer.setObjectName("qwer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.qwer.setText(_translate("MainWindow", "Сюда! окружность"))


class MyPrettyCalc(QMainWindow):
    def __init__(self):
        super(MyPrettyCalc, self).__init__()
        uic.loadUi('second.ui', self)
        self.qp = QPainter(self)
        self.qwer.clicked.connect(self.k)

    def k(self):
        self.update()

    def paintEvent(self, event) -> None:
        self.coords = random.randint(0, self.width()), random.randint(0, self.height())
        self.qp.begin(self)
        self.pen = QBrush(QColor(random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)))
        self.qp.setBrush(self.pen)
        self.qp.drawEllipse(self.coords[0], self.coords[1], a := random.randint(10, 70), a)
        self.qp.end()



if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyPrettyCalc()
    ex.show()
    sys.exit(app.exec())
